---
title: "R Notebook"
output: html_notebook
---

#Exercise 4 cont'd


```{r}
#a) y = x^3
f <- function(x){
  fx <- x^3
  return(fx)
}
input<- seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")

```

```{r}
#b) y = x^3 - 2x^2 - 3x +4
f <- function(x){
  fx <- x^3 - 2*x^2 - 3*x +4
  return(fx)
}
input<- seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")

```

```{r}
#c) y = 2x^3 - x + 5 
f <- function(x){
  fx <- 2*x^3 - x + 5 
  return(fx)
}
input<- seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")

```

```{r}
#d) y = x^3 - 3x^2 + 3x -1
f <- function(x){
  fx <- x^3 - 3*x^2 + 3*x -1
  return(fx)
}
input<- seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")

```

```{r}

#e) y = -x^3
f <- function(x){
  fx <- -x^3
  return(fx)
}
input<- seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")

```

```{r}
#f) y = -x^3 + 2x^2 + 3x -4
f <- function(x){
  fx <- -x^3 + 2*x^2 + 3*x -4
  return(fx)
}
input<-seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")

```

```{r}
#g) y = x^4
f <- function(x){
  fx <- x^4
  return(fx)
}
input<- seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")

```

```{r}
#h) y = x^4 - x^3 - x^2 + x + 1
f <- function(x){
  fx <- x^4 - x^3 - x^2 + x + 1
  return(fx)
}
input<- seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")

```

```{r}
#i) y = x^4 - 3x^3 + 2x^2 + x - 1
f <- function(x){
  fx <- x^4 - 3*x^3 + 2*x^2 + x - 1
  return(fx)
}
input<- seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")

```

```{r}
#j) y = y = x^4 - 4x^3 + 6x^2 - 4x
f <- function(x){
  fx <- x^4 - 4*x^3 + 6*x^2 - 4*x
  return(fx)
}
input<- seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")

```

```{r}
k) y = -x^4
{r}
f <- function(x){
  fx <- -x^4
  return(fx)
}
input<- seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")

```

```{r}
#l) y = -x^4 - 2x^3 + 3x
f <- function(x){
  fx <- -x^4 - 2*x^3 + 3*x
  return(fx)
}
input<- seq(-10 , 11 , 0.1 )
plot(input,sapply(input,f), type = "l", xlab = "x", ylab = "f(x)")
```

